### ISSUE TITLE
感谢分享您的项目！

### ISSUE THREAD

**Issue by ahojcn** [mydevc/go-gin-mvc#2]
https://github.com/mydevc/go-gin-mvc/blob/ce7a863a369d8d5d01f296a2ecf1469b883ccb90/models/orm.go#L62

我认为这里不可以是 len - 1，应该是 len。

**Comment by mydevc** [comment]
不客气，这是个demo，自己当初学习用的，没有商用过，谨慎参考，发现错误自行修改。另外我对go语言涉入不深，我的经历多为php的一些思维习惯。

**Comment by ahojcn** [comment]
> 不客气，这是个demo，自己当初学习用的，没有商用过，谨慎参考，发现错误自行修改。另外我对go语言涉入不深，我的经历多为php的一些思维习惯。

ok, 3q~
